// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHTCwR9XDS2jRlx_rWxUSqNMcufsAPitk',
    appId: '1:625045979992:web:e0cbe6d3beec7663925b2d',
    messagingSenderId: '625045979992',
    projectId: 'whatsapp-rivaan-144a3',
    authDomain: 'whatsapp-rivaan-144a3.firebaseapp.com',
    storageBucket: 'whatsapp-rivaan-144a3.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCRpHJ-bM9UTCRsf6rnCGuVL6lB_6B54g',
    appId: '1:625045979992:android:84775810d47b2cbc925b2d',
    messagingSenderId: '625045979992',
    projectId: 'whatsapp-rivaan-144a3',
    storageBucket: 'whatsapp-rivaan-144a3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZb6w13LIHPFrPvD-w5bCy5mb3A9QRoz8',
    appId: '1:625045979992:ios:589ccf86bf50ae37925b2d',
    messagingSenderId: '625045979992',
    projectId: 'whatsapp-rivaan-144a3',
    storageBucket: 'whatsapp-rivaan-144a3.appspot.com',
    androidClientId: '625045979992-6f0ebbvldvmig9jq8gdlm0ov39alm51g.apps.googleusercontent.com',
    iosClientId: '625045979992-o3l5evhbdt67ihludt99kedq0hdiaud4.apps.googleusercontent.com',
    iosBundleId: 'com.example.whatsappUi',
  );
}
